"""empty message

Revision ID: e6d9602e2325
Revises: 
Create Date: 2023-03-29 21:11:34.029652

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'e6d9602e2325'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre_name')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE genres SET SCHEMA {SCHEMA};")

    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_name', sa.String(), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=False),
    sa.Column('cast', sa.String(), nullable=False),
    sa.Column('writer', sa.String(length=500), nullable=False),
    sa.Column('movie_is', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('duration', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('prev_img', sa.String(), nullable=False),
    sa.Column('detail_img', sa.String(), nullable=False),
    sa.Column('trailer_src', sa.String(), nullable=False),
    sa.Column('netflix_original', sa.Boolean(), nullable=True),
    sa.Column('lex_top', sa.Boolean(), nullable=True),
    sa.Column('top_10', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE movies SET SCHEMA {SCHEMA};")

    op.create_table('tv_shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tv_name', sa.String(), nullable=False),
    sa.Column('creators', sa.String(length=500), nullable=False),
    sa.Column('cast', sa.String(), nullable=False),
    sa.Column('tv_is', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.String(length=40), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('prev_img', sa.String(), nullable=False),
    sa.Column('detail_img', sa.String(), nullable=False),
    sa.Column('trailer_src', sa.String(), nullable=False),
    sa.Column('num_seasons', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE tv_shows SET SCHEMA {SCHEMA};")

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    op.create_table('movie_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE movie_genres SET SCHEMA {SCHEMA};")
        
    op.create_table('tv_show_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE tv_show_genres SET SCHEMA {SCHEMA};")

    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('profile_img', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE profiles SET SCHEMA {SCHEMA};")

    op.create_table('tv_show_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('ep_number', sa.Integer(), nullable=False),
    sa.Column('ep_name', sa.String(), nullable=False),
    sa.Column('ep_description', sa.String(), nullable=False),
    sa.Column('ep_duration', sa.String(), nullable=False),
    sa.Column('ep_poster', sa.String(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tv_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE tv_show_episodes SET SCHEMA {SCHEMA};")

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")

    op.create_table('tv_show_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tv_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE tv_show_reviews SET SCHEMA {SCHEMA};")

    op.create_table('my_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('tv_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['tv_id'], ['tv_shows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movie_id'),
    sa.UniqueConstraint('tv_id')
    )
    if environment == "production":
        op.execute(f"ALTER TABLE my_list SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_list')
    op.drop_table('tv_show_reviews')
    op.drop_table('reviews')
    op.drop_table('tv_show_episodes')
    op.drop_table('profiles')
    op.drop_table('tv_show_genres')
    op.drop_table('movie_genres')
    op.drop_table('users')
    op.drop_table('tv_shows')
    op.drop_table('movies')
    op.drop_table('genres')
    # ### end Alembic commands ###
